# Get-FolderPermissions.ps1
# Reads NTFS permissions from one or more file servers for Projects* folders
# and their case subfolders (folders with a hyphen in the name).
# All results are combined into a single CSV.
# Run this on a machine that has network access to all listed servers.
#
# PREREQUISITES
# -------------
# 1. PowerShell 5.1 or later (built-in on Windows 10/Server 2016+). No extra modules needed.
#    Verify: $PSVersionTable.PSVersion
#
# 2. Execution policy must allow running local scripts.
#    If you get "running scripts is disabled" error, run once in an elevated PS window:
#      Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
#    Or bypass for a single run (no permanent change):
#      powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1
#
# 3. Network access to all servers listed in $Servers. Must be on domain or VPN.
#    Test first: Test-Path "\\SERVERNAME"
#
# 4. Read permission on the target folders. You do not need to be an administrator.
#    Folders you cannot read will be skipped with a warning.
#
# USAGE EXAMPLES
# --------------
# Default servers (edit $Servers below to match your environment):
#   powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1
#
# Override servers at runtime:
#   powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1 `
#     -Servers "\\CRCHFS1","\\CRNYFS2","\\CRDCFS1"
#
# Custom output file:
#   powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1 `
#     -OutputFile "C:\temp\perms.csv"

param(
    # List of UNC server roots to scan.
    # If not provided, the script reads them from output\servers.txt (generated by get_db_permissions.py).
    [Parameter(Mandatory = $false)]
    [string[]]$Servers = @(),

    [Parameter(Mandatory = $false)]
    [string]$OutputFile = ""
)

# Resolve paths inside script body so $MyInvocation is always populated
$ScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent
$OutputBase  = [System.IO.Path]::GetFullPath((Join-Path $ScriptRoot "..\output"))

if (-not $OutputFile) {
    $OutputFile = Join-Path $OutputBase "folder_permissions.csv"
}

# Load server list from servers.txt if not passed in as a parameter
if ($Servers.Count -eq 0) {
    $ServersFile = Join-Path $OutputBase "servers.txt"
    if (-not (Test-Path $ServersFile)) {
        Write-Error "No servers provided and '$ServersFile' not found.`nRun get_db_permissions.py first to generate the servers list."
        exit 1
    }
    $Servers = Get-Content $ServersFile | Where-Object { $_.Trim() -ne "" }
    Write-Host "Loaded $($Servers.Count) server(s) from servers.txt" -ForegroundColor Cyan
}

# ---------------------------------------------------------------------------
# Helper — read ACL for a folder and return one row per ACE
# ---------------------------------------------------------------------------

function Get-AclRows {
    param(
        [string]$Path,
        [string]$FolderType,
        [string]$FolderName,
        [string]$ParentProject,
        [string]$Server
    )

    try {
        $acl = Get-Acl -Path $Path -ErrorAction Stop
        foreach ($ace in $acl.Access) {
            [PSCustomObject]@{
                Server            = $Server
                FolderType        = $FolderType
                FolderPath        = $Path
                FolderName        = $FolderName
                ParentProject     = $ParentProject
                Owner             = $acl.Owner
                Identity          = $ace.IdentityReference.ToString()
                AccessControlType = $ace.AccessControlType.ToString()
                FileSystemRights  = $ace.FileSystemRights.ToString()
                IsInherited       = $ace.IsInherited
                InheritanceFlags  = $ace.InheritanceFlags.ToString()
                PropagationFlags  = $ace.PropagationFlags.ToString()
            }
        }
    }
    catch {
        Write-Warning "Cannot read ACL for '$Path': $_"
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

$outputDir = Split-Path $OutputFile -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$results = [System.Collections.Generic.List[PSCustomObject]]::new()
$totalServers  = $Servers.Count
$serversDone   = 0
$serversSkipped = 0

Write-Host "Servers to scan : $($Servers -join ', ')" -ForegroundColor Cyan
Write-Host "Output file     : $OutputFile" -ForegroundColor Cyan
Write-Host ""

foreach ($server in $Servers) {

    Write-Host "[$($serversDone + 1)/$totalServers] Scanning $server ..." -ForegroundColor Cyan

    # Verify the server is reachable before trying to enumerate
    if (-not (Test-Path $server -ErrorAction SilentlyContinue)) {
        Write-Warning "  Cannot reach $server - skipping."
        $serversSkipped++
        continue
    }

    $projectFolders = Get-ChildItem -Path $server -Directory -Filter "Projects*" -ErrorAction SilentlyContinue

    if (-not $projectFolders) {
        Write-Warning "  No 'Projects*' folders found at $server - skipping."
        $serversSkipped++
        continue
    }

    Write-Host "  Found $($projectFolders.Count) Project folder(s)" -ForegroundColor Green

    foreach ($proj in $projectFolders) {
        Write-Host "    Project: $($proj.Name)" -ForegroundColor Yellow

        # Permissions on the project folder itself
        Get-AclRows -Path $proj.FullName -FolderType "Project" `
                    -FolderName $proj.Name -ParentProject "" -Server $server |
            ForEach-Object { $results.Add($_) }

        # Case folders — any subfolder whose name contains a hyphen
        $caseFolders = Get-ChildItem -Path $proj.FullName -Directory -ErrorAction SilentlyContinue |
                       Where-Object { $_.Name -match '-' }

        if ($caseFolders) {
            Write-Host "      $($caseFolders.Count) case folder(s)" -ForegroundColor Gray
        }

        foreach ($case in $caseFolders) {
            Get-AclRows -Path $case.FullName -FolderType "Case" `
                        -FolderName $case.Name -ParentProject $proj.Name -Server $server |
                ForEach-Object { $results.Add($_) }
        }
    }

    $serversDone++
}

# Export all results into one CSV
$results | Export-Csv -Path $OutputFile -NoTypeInformation -Encoding UTF8

Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Green
Write-Host "  Servers scanned : $serversDone / $totalServers ($serversSkipped skipped)"
Write-Host "  Total rows      : $($results.Count)"
Write-Host "  Output          : $OutputFile" -ForegroundColor Green
