# Get-FolderPermissions.ps1
# Reads NTFS permissions from one or more file servers for Projects* folders
# and their case subfolders (folders with a hyphen in the name).
# All results are combined into a single CSV.
# Run this on a machine that has network access to all listed servers.
#
# PREREQUISITES
# -------------
# 1. PowerShell 5.1 or later (built-in on Windows 10/Server 2016+). No extra modules needed.
#    Verify: $PSVersionTable.PSVersion
#
# 2. Execution policy must allow running local scripts.
#    If you get "running scripts is disabled" error, run once in an elevated PS window:
#      Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
#    Or bypass for a single run (no permanent change):
#      powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1
#
# 3. Network access to all servers listed in $Servers. Must be on domain or VPN.
#    Test first: Test-Path "\\SERVERNAME"
#
# 4. Read permission on the target folders. You do not need to be an administrator.
#    Folders you cannot read will be skipped with a warning.
#
# USAGE EXAMPLES
# --------------
# Default servers (edit $Servers below to match your environment):
#   powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1
#
# Override servers at runtime:
#   powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1 `
#     -Servers "\\CRCHFS1","\\CRNYFS2","\\CRDCFS1"
#
# Custom output file:
#   powershell -ExecutionPolicy Bypass -File .\Get-FolderPermissions.ps1 `
#     -OutputFile "C:\temp\perms.csv"

param(
    # List of \\SERVER\ProjectsXXX project paths to scan.
    # If not provided, reads from output\project_paths.txt (generated by get_db_permissions.py).
    [Parameter(Mandatory = $false)]
    [string[]]$ProjectPaths = @(),

    [Parameter(Mandatory = $false)]
    [string]$OutputFile = ""
)

# Resolve paths inside script body so $MyInvocation is always populated
$ScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent
$OutputBase  = [System.IO.Path]::GetFullPath((Join-Path $ScriptRoot "..\output"))

if (-not $OutputFile) {
    $OutputFile = Join-Path $OutputBase "folder_permissions.csv"
}

# Load project paths from project_paths.txt if not passed in as a parameter
if ($ProjectPaths.Count -eq 0) {
    $ProjectPathsFile = Join-Path $OutputBase "project_paths.txt"
    if (-not (Test-Path $ProjectPathsFile)) {
        Write-Error "'$ProjectPathsFile' not found.`nRun get_db_permissions.py first to generate the project paths list."
        exit 1
    }
    $ProjectPaths = Get-Content $ProjectPathsFile | Where-Object { $_.Trim() -ne "" }
    Write-Host "Loaded $($ProjectPaths.Count) project path(s) from project_paths.txt" -ForegroundColor Cyan
}

# ---------------------------------------------------------------------------
# Helper — read ACL for a folder and return one row per ACE
# ---------------------------------------------------------------------------

function Get-AclRows {
    param(
        [string]$Path,
        [string]$FolderType,
        [string]$FolderName,
        [string]$ParentProject,
        [string]$Server
    )

    try {
        $acl = Get-Acl -Path $Path -ErrorAction Stop
        foreach ($ace in $acl.Access) {
            [PSCustomObject]@{
                FolderPath        = $Path
                FolderType        = $FolderType
                Identity          = $ace.IdentityReference.ToString()
                AccessControlType = $ace.AccessControlType.ToString()
                IsInherited       = $ace.IsInherited
            }
        }
    }
    catch {
        Write-Warning "Cannot read ACL for '$Path': $_"
        [PSCustomObject]@{
            FolderPath        = $Path
            FolderType        = "NO_ACCESS"
            Identity          = "NO_ACCESS"
            AccessControlType = "NO_ACCESS"
            IsInherited       = "NO_ACCESS"
        }
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

$outputDir = Split-Path $OutputFile -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$results       = [System.Collections.Generic.List[PSCustomObject]]::new()
$totalPaths    = $ProjectPaths.Count
$pathsDone     = 0
$pathsSkipped  = 0

Write-Host "Project paths to scan : $totalPaths" -ForegroundColor Cyan
Write-Host "Output file           : $OutputFile" -ForegroundColor Cyan
Write-Host ""

foreach ($projPath in $ProjectPaths) {

    $projName  = Split-Path $projPath -Leaf
    $server    = Split-Path $projPath -Parent

    Write-Host "[$($pathsDone + 1)/$totalPaths] $projPath" -ForegroundColor Yellow

    # Case folders — subfolders whose name contains a hyphen
    $caseFolders = Get-ChildItem -Path $projPath -Directory -ErrorAction SilentlyContinue |
                   Where-Object { $_.Name -match '-' }

    if (-not $caseFolders) {
        Write-Warning "  No case folders found (or no access) - skipping."
        $pathsSkipped++
        $pathsDone++
        continue
    }

    Write-Host "  $($caseFolders.Count) case folder(s)" -ForegroundColor Gray

    foreach ($case in $caseFolders) {
        Get-AclRows -Path $case.FullName -FolderType "Case" `
                    -FolderName $case.Name -ParentProject $projName -Server $server |
            ForEach-Object { $results.Add($_) }
    }

    $pathsDone++
}

# Export all results into one CSV
$results | Export-Csv -Path $OutputFile -NoTypeInformation -Encoding UTF8

Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Green
Write-Host "  Paths scanned : $pathsDone / $totalPaths ($pathsSkipped with no case folders)"
Write-Host "  Total rows    : $($results.Count)"
Write-Host "  Output        : $OutputFile" -ForegroundColor Green
